openapi: 3.0.0
info:
  title: My API Documentation
  version: 1.0.0
  description: API documentation for my Node.js project
servers:
  - url: "http://localhost:4000"
    description: Development server

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                required:
                  - userId
        '400':
          description: Bad request (validation errors)
        '500':
          description: Internal server error

  /auth/login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login successful"
                  token:
                    type: string
                    example: "your_jwt_token_here"
        '400':
          description: Bad request (invalid credentials)
        '401':
          description: Unauthorized (incorrect credentials)
        '500':
          description: Internal server error

components:
  schemas:
    User:
      type: object
      properties:
        userId:
          type: string
    Login:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
