name: Health Test

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 8.0

      - name: Install Dependenices
        run: |
          cd backend
          npm install

      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB to be ready..."
          while ! mongo --host mongodb --username root --password example --eval "print(\"waited for connection\")"; do
            sleep 1
          done

      - name: Run Tests
        run: |
          cd backend
          npm test

      - name: Deploy to development
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to development..."

      
