name: Health Test

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        options: >-
          --health-cmd "echo 'exit' | mongo --username root --password example --host mongodb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependenices
        run: |
          cd backend
          npm install

      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB to be ready..."
          while ! mongo --host mongodb --username root --password example --eval "print(\"waited for connection\")"; do
            sleep 1
          done

      - name: Run Tests
        run: |
          cd backend
          npm test

      - name: Deploy to development
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to development..."

      
